algoritmo "EX 4"
// Disciplina  :  [Linguagem e Técnicas de Programação]
// Professor   : Rogério
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/08
var

B, H, BA, AT: real

inicio

escreval("Digite o valor da Base do Triangulo: ")
leia(B)
escreval("Digite o valor da Altura do Triangulo: ")
leia(H)

BA <-(B*H)
AT <-(BA/2)

escreval("A Área do Triangulo é: ", AT)
fimalgoritmo