algoritmo "Ex 3"
// Disciplina  :  [Linguagem e Técnicas de Programação]
// Professor   : [Rogério]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/08 

var

Sal, NSal, Aum: Real

inicio

escreval("Qual seu salário? ")
leia(Sal)

Aum <- (Sal*0.1)
NSal <- (Sal+Aum)

escreval("O aumento será de R$", Aum)
escreva("E seu novo salário será de R$", NSal)

fimalgoritmo