algoritmo "Ex2"
// Disciplina  :  [Linguagem e Técnicas de Programação]
// Professor   : Rogério
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/08
var

N1, N2, M: Inteiro

inicio

escreval("Qual a primeira nota? ")
leia(N1)
escreval("E qual a segunda nota? ")
leia(N2)

M <- ((N1+N2)/2)

escreva("A média será ", M)

fimalgoritmo